### ISSUE TITLE
Phone mirroring not working

### ISSUE THREAD

**Issue by Sinbrad** [BimmerGestalt/IDriveConnectAddons#20]
Installed AAIDRIVE and mirrorlink apk. Mirror shows up on infotainment screen, try to open it states opening but get message saying to allow app permissions for screen writing or something similar but unable to do so and I have to exit. Help

**Comment by hufman** [comment]
When you open this screen in the car, your phone should show a notification requesting permission. Otherwise, you can go to the AAIdrive Addons tab and tap the settings button for Screen Mirroring, and there should be a button in that new screen to grant permission.

**Comment by Sinbrad** [comment]
Got it working but very slow. Also, no touch screen movement, I take it touchscreen is not an option?

**Comment by hufman** [comment]
Yes, it's very slow because the Bluetooth protocol has low bandwidth and the car only accepts full images in that widget, there's no way to stream a video over the protocol AAIdrive uses.
The car also doesn't send any touch events over the protocol, only button events, and I haven't found any way for AAIdrive to forward these events to other apps on the phone without violating TOS.
I'm glad it's working for you now!
