### ISSUE TITLE
Screen Mirror fps

### ISSUE THREAD

**Issue by Krakuanen** [BimmerGestalt/IDriveConnectAddons#8]
I've read that the Android Auto app is to be discontinued. Is there a way to use Screen Mirror without the fps cap when not using the Android Auto app?

**Comment by hufman** [comment]
Good morning! That is disappointing to hear!
Android doesn't provide a good way to tell what app is in the foreground :( The Android Auto detection [checks a global Car UI Mode flag](https://github.com/BimmerGestalt/IDriveConnectAddons/blob/1034898d866f55369c0747b646c36ece6f23a497/screen_mirror/src/main/java/io/bimmergestalt/idriveconnectaddons/screenmirror/carapp/CarApp.kt#L193), and doesn't provide any further options.
I did update Screen Mirroring to go at 1fps instead of 0.5fps while in motion a few months ago, are you using that version?

**Comment by Krakuanen** [comment]
I use the latest build, so it's 1 fps when not using Android Auto. It's "Android Auto for phone screen" that's to be discontinued, not sure if that's the version I use though. Everything is working great as it is now. Thank you for your great work!

**Comment by Krakuanen** [comment]
Android Auto has now been discontinued. When it is opened there is an information notice that it can't be used and then it closes down.

**Comment by Xardas2000** [comment]
@hufman Hi! can you explain, why is needed to decrease fps while car is move?

**Comment by hufman** [comment]
Hi! It's a simple reason: I don't want to encourage distracted driving by enabling video watching at full speed, while the 1fps is a good compromise to allow for navigation apps.

**Comment by Xardas2000** [comment]
@hufman thanks for explain. But i think, in town traffic 1fps is to small, and people can use screen mirroring for cast films by default screen mirroring. But your solve allow to use screen mirroring with radio/music.

Please, consider to increase fps for real-time.

**Comment by hufman** [comment]
Screen Mirroring is a much better solution, of course, if the car supports it. BMW does not enable it in most markets, but it uses a much more efficient protocol (WiFi instead of Bluetooth) and performs much better.
Are you experiencing slow frame updates while parked too? That's just a limitation of Bluetooth's latency, I rarely get more than 5fps even with the terrible JPG quality.
1fps should be plenty while driving around town, especially at low speeds. It's only meant for navigation apps, especially because there isn't any input support, with the Music apps usecase handled by AAIdrive directly.

**Comment by Xardas2000** [comment]
@hufman year, i know about Bluetooth limitation. I tried to reduce 1fps to 0 and built this and for me it works better:)

**Comment by Igor176** [comment]
> @hufman year, i know about Bluetooth limitation. I tried to reduce 1fps to 0 and built this and for me it works better:)

Greetings. You can throw off your modified version with 0 fps. I launched the Yandex Maps card waiting application, but because of the delay, it is not comfortable to use it.

**Comment by znarf77** [comment]
Sorry if I come back to this discussion, is there any udpate or news on how to speed up the mirroring or any update about android  auto? The std navigator is driving me mad!  :-)

**Comment by hufman** [comment]
Sorry, there have been no updates. BMW Apps are still only supported over USB or Bluetooth and can not be faster, and there is no input support from the car's touchscreen. AAIdrive is at the limit of what is possible with this BMW protocol. There are MMI boxes you could mod into the car to enable true Android Auto support, but I haven't tried them because I prefer the (colorful Mini theme) look of the IDrive system :)

**Comment by znarf77** [comment]
> Sorry, there have been no updates. BMW Apps are still only supported over USB or Bluetooth and can not be faster, and there is no input support from the car's touchscreen. AAIdrive is at the limit of what is possible with this BMW protocol. There are MMI boxes you could mod into the car to enable true Android Auto support, but I haven't tried them because I prefer the (colorful Mini theme) look of the IDrive system :)

Ok, I was reading in the previous post that the FPS could be modified and I was thinking to increase them in order to do perform android maps mirroring

**Comment by hufman** [comment]
This addon does enforce a frame rate cap while the speedometer is more than 0, and yes that's just a bit of code and you can change it. However, while stopped, it sends frames as fast as possible, which over Bluetooth is still very slow. You could get faster frame rates over USB, except MyBMW is buggy with USB, and other audio side effects. Besides screen mirroring while parked, AAIdrive's map module always sends at full speed, which is still not fast.
There is nothing to be done to speed this up.
